<?xml version="1.0"?>
<package format="2">
  <name>shared_msgs</name>
  <version>0.0.1</version>
  <description>Shared message definitions for ROS1 and ROS2 bridge</description>

  <maintainer email="you@example.com">your_name</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>message_generation</build_depend>
  <exec_depend>message_runtime</exec_depend>

  <depend>std_msgs</depend>

</package>