volumes:
  ros_test_shared:
  gui_home:
  
services:
  ros-master:
    build:
      context: ./ros-master
      args:
        - BASE_IMAGE=${ROS1_BASE_IMAGE}
    container_name: ros-master
    hostname: ros-master
    environment:
      - ROS_MASTER_URI=http://${ROS_MASTER_HOSTNAME}:${ROS_MASTER_PORT}
      - ROS_HOSTNAME=ros-master
    networks:
      - rosnet
  robot_p3at_sim_ros1:
    build:
      context: ./robot_p3at_sim_ros1
      args:
        - BASE_IMAGE=${ROS1_BASE_IMAGE}
    depends_on:
      - ros-master
      - gazebo
    container_name: robot_p3at_sim_ros1
    environment:
      - ROS_MASTER_URI=http://${ROS_MASTER_HOSTNAME}:${ROS_MASTER_PORT}
      - ROS_HOSTNAME=robot_p3at_sim_ros1
      - STRATEGY=${STRATEGY}
      - ROBOT_NAMESPACE=${ROBOT_P3AT_ROS1_NAMESPACE}
    networks:
      - rosnet
  gui-desktop:
    image: tiryoh/ros-desktop-vnc:noetic
    container_name: gui-desktop
    hostname: gui-desktop
    shm_size: "512mb"
    environment:
      - ROS_MASTER_URI=http://${ROS_MASTER_HOSTNAME}:${ROS_MASTER_PORT}
      - ROS_HOSTNAME=gui-desktop
    ports:
      - "8080:80"
    networks:
      - rosnet
    volumes:
      - gui_home:/home/ubuntu
    command: >
      bash -c "
        mkdir -p /home/ubuntu/.gazebo &&
        chown -R ubuntu:ubuntu /home/ubuntu &&
        /startup.sh
      "
  gazebo:
    build:
      context: ./gazebo_classic
      args:
        - BASE_IMAGE=${ROS1_BASE_IMAGE}
    container_name: gazebo
    depends_on:
      - ros-master
      - gui-desktop
    network_mode: "service:gui-desktop"
    ipc: host
    #user: "1000:1000"
    environment:
      - ROS_MASTER_URI=http://${ROS_MASTER_HOSTNAME}:${ROS_MASTER_PORT}
      - DISPLAY=:1
      - HOME=/home/ubuntu
      - XAUTHORITY=/home/ubuntu/.Xauthority
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=1
      - XDG_RUNTIME_DIR=/tmp/runtime-ubuntu
    volumes:
      - gui_home:/home/ubuntu
      - ./gazebo_classic/worlds:/home/ubuntu/worlds
      - ./gazebo_classic/models:/home/ubuntu/.gazebo/models
      - ./gazebo_classic/robots:/home/ubuntu/robots
      - ./gazebo_classic/launch:/home/ubuntu/launch
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: >
      bash -c "
        mkdir -p /home/ubuntu/.gazebo &&
        chown -R 1000:1000 /home/ubuntu &&
        roslaunch /home/ubuntu/launch/simulation.launch \
          world_file:=${GAZEBO_WORLD_FILE} \
          robot_file:=/home/ubuntu/robots/${ROBOT_MODEL_FILE} \
          gui:=${GAZEBO_GUI_ENABLED}
      "
  robot_p3at_sim_ros2:
    build:
      context: ./robot_p3at_sim_ros2
      args:
        - BASE_IMAGE=${ROS2_BASE_IMAGE}
    container_name: robot_p3at_sim_ros2
    hostname: robot_p3at_sim_ros2
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROBOT_P3AT_ROS1_NAMESPACE=${ROBOT_P3AT_ROS1_NAMESPACE}
      - ROBOT_P3AT_ROS2_NAMESPACE=${ROBOT_P3AT_ROS2_NAMESPACE}
    volumes:
      - ros_test_shared:/ros_test_shared
    networks:
      - rosnet

  ros_bridge:
    build:
      context: ./ros_bridge
      args:
        - BASE_IMAGE=${ROS2_BASE_IMAGE}
    container_name: ros_bridge
    hostname: ros_bridge
    depends_on:
      - ros-master
      - robot_p3at_sim_ros1
      - robot_p3at_sim_ros2
    environment:
      - ROS_MASTER_URI=http://${ROS_MASTER_HOSTNAME}:${ROS_MASTER_PORT}
      - ROS_HOSTNAME=ros_bridge
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ./ros_bridge/bridge_mappings.yaml:/bridge_mappings.yaml
    networks:
      - rosnet

  ros_tests:
    profiles: ["test"]
    build:
      context: ./ros_tests
      args:
        - BASE_IMAGE=${ROS2_BASE_IMAGE}
    container_name: ros_tests
    depends_on:
      - robot_p3at_sim_ros1
      - robot_p3at_sim_ros2
      - ros_bridge
    networks:
      - rosnet
    environment:
      - ROS_MASTER_URI=http://${ROS_MASTER_HOSTNAME}:${ROS_MASTER_PORT}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROBOT_P3AT_ROS1_NAMESPACE=${ROBOT_P3AT_ROS1_NAMESPACE}
      - ROBOT_P3AT_ROS2_NAMESPACE=${ROBOT_P3AT_ROS2_NAMESPACE}
    volumes:
      - ros_test_shared:/ros_test_shared

  robot_unitree_go2_ros2:
    build:
      context: ./robot_unitree_go2_ros2
      args:
        - BASE_IMAGE=${ROS2_BASE_IMAGE}
    container_name: robot_unitree_go2_ros2
    hostname: robot_unitree_go2_ros2
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROBOT_NAMESPACE=${ROBOT_GO2_ROS2_NAMESPACE}
    depends_on:
      - ros_bridge
    networks:
      - rosnet

networks:
  rosnet:
    driver: bridge

