volumes:
  ros_test_shared:

services:
  ros-master:
    build:
      context: ./ros-master
      args:
        - BASE_IMAGE=${ROS1_BASE_IMAGE}
    container_name: ros-master
    hostname: ros-master
    environment:
      - ROS_MASTER_URI=http://${ROS_MASTER_HOSTNAME}:${ROS_MASTER_PORT}
      - ROS_HOSTNAME=ros-master
    networks:
      - rosnet
  robot_p3at_sim_ros1:
    build:
      context: ./robot_p3at_sim_ros1
      args:
        - BASE_IMAGE=${ROS1_BASE_IMAGE}
    depends_on:
      - ros-master
      - gazebo
    container_name: robot_p3at_sim_ros1
    environment:
      - ROS_MASTER_URI=http://${ROS_MASTER_HOSTNAME}:${ROS_MASTER_PORT}
      - ROS_HOSTNAME=robot_p3at_sim_ros1
      - STRATEGY=${STRATEGY}
      - ROBOT_NAMESPACE=${ROBOT_ROS1_NAMESPACE}
    networks:
      - rosnet
  gui-desktop:
    image: tiryoh/ros-desktop-vnc:noetic
    container_name: gui-desktop
    hostname: gui-desktop
    shm_size: "512mb"
    environment:
      - ROS_MASTER_URI=http://${ROS_MASTER_HOSTNAME}:${ROS_MASTER_PORT}
      - ROS_HOSTNAME=gui-desktop
      - XHOST_DISABLE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8080:80"
    networks:
      - rosnet
  gazebo:
    build:
      context: ./gazebo_classic
      args:
        - BASE_IMAGE=${ROS1_BASE_IMAGE}
    container_name: gazebo
    hostname: gazebo
    depends_on:
      - ros-master
    environment:
      - ROS_MASTER_URI=http://${ROS_MASTER_HOSTNAME}:${ROS_MASTER_PORT}
      - ROS_HOSTNAME=gazebo
      # Variables de entorno gráficas
      - DISPLAY=${HOST_DISPLAY}
      - QT_X11_NO_MITSHM=1
      - LIBGL_ALWAYS_SOFTWARE=${LIBGL_ALWAYS_SOFTWARE:-0}
      - XAUTHORITY=/root/.Xauthority
    volumes:
      - ./gazebo_classic/worlds:/root/worlds
      - ./gazebo_classic/models:/root/.gazebo/models
      - ./gazebo_classic/robots:/root/robots
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    networks:
      - rosnet
    command: [
      "roslaunch", 
      "/root/worlds/simulation.launch", 
      "world_file:=${GAZEBO_WORLD_FILE}",
      "robot_file:=/root/robots/${ROBOT_MODEL_FILE}",
      "gui:=${GAZEBO_GUI_ENABLED}"
    ]

  robot_p3at_sim_ros2:
    build:
      context: ./robot_p3at_sim_ros2
      args:
        - BASE_IMAGE=${ROS2_BASE_IMAGE}
    container_name: robot_p3at_sim_ros2
    hostname: robot_p3at_sim_ros2
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROBOT_ROS1_NAMESPACE=${ROBOT_ROS1_NAMESPACE}
      - ROBOT_ROS2_NAMESPACE=${ROBOT_ROS2_NAMESPACE}
    volumes:
      - ros_test_shared:/ros_test_shared
    networks:
      - rosnet

  ros2_bridge:
    build:
      context: ./ros2_bridge
      args:
        - BASE_IMAGE=${ROS2_BASE_IMAGE}
    container_name: ros2_bridge
    hostname: ros2_bridge
    depends_on:
      - ros-master
      - robot_p3at_sim_ros1
      - robot_p3at_sim_ros2
    environment:
      - ROS_MASTER_URI=http://${ROS_MASTER_HOSTNAME}:${ROS_MASTER_PORT}
      - ROS_HOSTNAME=ros2_bridge
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - ./ros2_bridge/bridge_mappings.yaml:/bridge_mappings.yaml
    networks:
      - rosnet

  ros_tests:
    profiles: ["test"]
    build:
      context: ./ros_tests
      args:
        - BASE_IMAGE=${ROS2_BASE_IMAGE}
    depends_on:
      - robot_p3at_sim_ros1
      - robot_p3at_sim_ros2
      - ros2_bridge
    networks:
      - rosnet
    environment:
      - ROS_MASTER_URI=http://${ROS_MASTER_HOSTNAME}:${ROS_MASTER_PORT}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROBOT_ROS1_NAMESPACE=${ROBOT_ROS1_NAMESPACE}
      - ROBOT_ROS2_NAMESPACE=${ROBOT_ROS2_NAMESPACE}
    volumes:
      - ros_test_shared:/ros_test_shared

networks:
  rosnet:
    driver: bridge